name: Fetch PR Data

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  fetch-prs:  # ✅ Indentation fixed
    runs-on: ubuntu-latest  # ✅ Correctly indented

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytz PyGithub

      - name: Run Fetch PR Data Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python fetch_pr_data.py

      - name: Upload CSV as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: pull_requests_csv
          path: pull_requests.csv
